import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({repo}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         {repo.stargazers_count}
        </h1>
      </main>
    </div>
  )
}

export const getStaticProps = (async (context) => {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const repo = await res.json()
  return { props: { repo } }
})
